"""Non nullable customer name in invoice model

Revision ID: 25890073a78f
Revises: 1e9010cdc101
Create Date: 2025-06-17 10:48:15.954656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25890073a78f'
down_revision: Union[str, Sequence[str], None] = '1e9010cdc101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'customer_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'customer_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
